/*
 * TrentRoots2.java
 *
 * Created on November 11, 2002, 7:14 PM
 */

import javax.swing.JTextField;
import javax.swing.JTextArea;

/**
 *
 * @author  default
 */
public class TrentRoots2 extends javax.swing.JFrame {
    
    /** Creates new form TrentRoots2 */
    public TrentRoots2() {
        setTitle("TrentRoots 2.0!");
        setResizable(false);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        firstButton = new javax.swing.JRadioButton();
        secondButton = new javax.swing.JRadioButton();
        thirdButton = new javax.swing.JRadioButton();
        pteLabel = new javax.swing.JLabel();
        pteFirstTextField = new javax.swing.JTextField();
        pteSecondTextField = new javax.swing.JTextField();
        pteThirdTextField = new javax.swing.JTextField();
        ptrLabel = new javax.swing.JLabel();
        ptrFirstTextField = new javax.swing.JTextField();
        ptrSecondTextField = new javax.swing.JTextField();
        ptrThirdTextField = new javax.swing.JTextField();
        trLabel = new javax.swing.JLabel();
        trFirstTextField = new javax.swing.JTextField();
        trSecondTextField = new javax.swing.JTextField();
        trThirdTextField = new javax.swing.JTextField();
        genButton = new javax.swing.JButton();
        selButton = new javax.swing.JButton();
        htmlArea = new javax.swing.JTextArea();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        firstButton.setMnemonic('1');
        buttonGroup1.add(firstButton);
        firstButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        firstButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        getContentPane().add(firstButton, gridBagConstraints);

        secondButton.setMnemonic('2');
        buttonGroup1.add(secondButton);
        secondButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secondButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        secondButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        getContentPane().add(secondButton, gridBagConstraints);

        thirdButton.setMnemonic('3');
        buttonGroup1.add(thirdButton);
        thirdButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thirdButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thirdButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 6);
        getContentPane().add(thirdButton, gridBagConstraints);

        pteLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        pteLabel.setText("Proto-Terras");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        getContentPane().add(pteLabel, gridBagConstraints);

        pteFirstTextField.setColumns(10);
        pteFirstTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 6);
        getContentPane().add(pteFirstTextField, gridBagConstraints);

        pteSecondTextField.setColumns(10);
        pteSecondTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 6);
        getContentPane().add(pteSecondTextField, gridBagConstraints);

        pteThirdTextField.setColumns(10);
        pteThirdTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 6);
        getContentPane().add(pteThirdTextField, gridBagConstraints);

        ptrLabel.setText("Proto-Trentish");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        getContentPane().add(ptrLabel, gridBagConstraints);

        ptrFirstTextField.setColumns(10);
        ptrFirstTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 6);
        getContentPane().add(ptrFirstTextField, gridBagConstraints);

        ptrSecondTextField.setColumns(10);
        ptrSecondTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 6);
        getContentPane().add(ptrSecondTextField, gridBagConstraints);

        ptrThirdTextField.setColumns(10);
        ptrThirdTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 6);
        getContentPane().add(ptrThirdTextField, gridBagConstraints);

        trLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        trLabel.setText("Trentish");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 6);
        getContentPane().add(trLabel, gridBagConstraints);

        trFirstTextField.setColumns(10);
        trFirstTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 6);
        getContentPane().add(trFirstTextField, gridBagConstraints);

        trSecondTextField.setColumns(10);
        trSecondTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 6);
        getContentPane().add(trSecondTextField, gridBagConstraints);

        trThirdTextField.setColumns(10);
        trThirdTextField.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 6);
        getContentPane().add(trThirdTextField, gridBagConstraints);

        genButton.setMnemonic('G');
        genButton.setText("Generate");
        genButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateAction(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 5, 5);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        getContentPane().add(genButton, gridBagConstraints);

        selButton.setMnemonic('S');
        selButton.setText("Select");
        selButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAction(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(selButton, gridBagConstraints);

        htmlArea.setRows(4);
        htmlArea.setBorder(new javax.swing.border.EtchedBorder());
        htmlArea.setLineWrap(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        getContentPane().add(htmlArea, gridBagConstraints);

        pack();
    }//GEN-END:initComponents

    private int doSelect(javax.swing.ButtonModel selec)
    {   if (selec == null) 
        { htmlArea.setText("Select a root."); 
          return 0;
        }

        if (selec.getMnemonic() == 49)
          return 0;
        else if (selec.getMnemonic() == 50)
          return 1;
        else 
          return 2;
    }
    

    private void selectAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectAction
        // Add your handling code here:
        javax.swing.ButtonModel selec = buttonGroup1.getSelection();
        
        int sel = doSelect(selec);
      
        String[] trOutcomes = { tf(trFirstTextField.getText()), tf(trSecondTextField.getText()), tf(trThirdTextField.getText()) };
        String[] ptrOutcomes = { tf(ptrFirstTextField.getText()), tf(ptrSecondTextField.getText()), tf(ptrThirdTextField.getText()) };
        String[] pteOutcomes = { tf(pteFirstTextField.getText()), tf(pteSecondTextField.getText()), tf(pteThirdTextField.getText()) };

        StringBuffer out = new StringBuffer("<dt>" + trOutcomes[sel] + "\n<dd>[&gamma;]     [PTr" + (ptrOutcomes[sel].equals(trOutcomes[sel]) ? "," : " <i>*" + ptrOutcomes[sel] + "</i>") + " &lt; PTe" + ((ptrOutcomes[sel].equals(pteOutcomes[sel]) ? ", <i>**" : " <i>*" + pteOutcomes[sel] + ", **") + pteOutcomes[(sel + 1) % 3] + "/**" + pteOutcomes[(sel + 2) % 3] + "</i>.]" )  );
        
        htmlArea.setText(new String(out));
    }//GEN-LAST:event_selectAction

    private String tf(String papa)
    { papa = papa.replaceAll("N", "&#331;");
      papa = papa.replaceAll("J", "&ntilde;");
      papa = papa.replaceAll("V:", "&#652;&#652;");
      papa = papa.replaceAll("V", "&#652;");
      papa = papa.replaceAll("’", "\\'");
      papa = papa.replaceAll("A", "&#593;");
      papa = papa.replaceAll("\\?", "&#660;");
      papa = papa.replaceAll("K", "l");
      papa = papa.replaceAll("S", "&scaron;");
      papa = papa.replaceAll("U", "&#650;");
      papa = papa.replaceAll("O", "&#596;");
      papa = papa.replaceAll("ø", "&oslash;");
      
      return papa;
    }
    
    private void generateAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateAction
        // Add your handling code here:
        // Add your handling code here:
        formRoots(pteFirstTextField, ptrFirstTextField, trFirstTextField);
        formRoots(pteSecondTextField, ptrSecondTextField, trSecondTextField);
        formRoots(pteThirdTextField, ptrThirdTextField, trThirdTextField);
          
    }//GEN-LAST:event_generateAction

    private void mutate(String mod, JTextField pTrentTextField, JTextField trentTextField)
    {   // P-Terr > P-Trent
        
        mod = mod.replaceAll("i:", "ji");
        mod = mod.replaceAll("e:", "je");
        mod = mod.replaceAll("a:", "jA");
        mod = mod.replaceAll("o:", "wo");
        mod = mod.replaceAll("u:", "wu");
        mod = mod.replaceAll("a", "A");
        mod = mod.replaceAll("rl:", "VrVr");
        mod = mod.replaceAll("rl", "Vr");
        mod = mod.replaceAll("l:", "V:");
        mod = mod.replaceAll("lA", "wA");
        mod = mod.replaceAll("le", "we");
        mod = mod.replaceAll("li", "wi");
        mod = mod.replaceAll("lo", "jo");
        mod = mod.replaceAll("lu", "ju");
        mod = mod.replaceAll("l", "V");
        mod = mod.replaceAll("r", "l");

        pTrentTextField.setText(mod);
        
        // P-Trent > Trent
        mod = mod.replaceAll("wi", "wy");
        mod = mod.replaceAll("we", "wø");
        mod = mod.replaceAll("ju", "jU");
        mod = mod.replaceAll("jo", "jO");
        mod = mod.replaceAll("h", "");
        mod = mod.replaceAll("ie", "je");
        mod = mod.replaceAll("ii", "ji");
        mod = mod.replaceAll("ia", "ja");
        mod = mod.replaceAll("io", "jo");
        mod = mod.replaceAll("iu", "ju");
        mod = mod.replaceAll("iV", "jV");
        mod = mod.replaceAll("ue", "we");
        mod = mod.replaceAll("ui", "wi");
        mod = mod.replaceAll("ua", "wa");
        mod = mod.replaceAll("uo", "wo");
        mod = mod.replaceAll("uu", "wu");
        mod = mod.replaceAll("uV", "wV");
        mod = mod.replaceAll("lw", "l");
        mod = mod.replaceAll("lj", "S");
        mod = mod.replaceAll("cl", "K");
        mod = mod.replaceAll("tl", "K");
        mod = mod.replaceAll("pl", "S");
        mod = mod.replaceAll("kl", "x");
        mod = mod.replaceAll("pj", "F");
        mod = mod.replaceAll("tj", "T");
        mod = mod.replaceAll("cj", "C");
        mod = mod.replaceAll("kj", "X");
        mod = mod.replaceAll("p", "b");
        mod = mod.replaceAll("t", "d");
        mod = mod.replaceAll("c", "S");
        mod = mod.replaceAll("k", "g");
        mod = mod.replaceAll("F", "ph");
        mod = mod.replaceAll("T", "th");
        mod = mod.replaceAll("C", "ch");
        mod = mod.replaceAll("X", "kh");
        mod = mod.replaceAll("wy", "y");
        mod = mod.replaceAll("wø", "ø");
        mod = mod.replaceAll("jU", "U");
        mod = mod.replaceAll("jO", "O");
        mod = mod.replaceAll("^qt", "q");
        mod = mod.replaceAll("qp", "p");
        mod = mod.replaceAll("qt", "t");
        mod = mod.replaceAll("qc", "c");
        mod = mod.replaceAll("qk", "k");
        mod = mod.replaceAll("b", "p’");
        mod = mod.replaceAll("d", "t’");
        mod = mod.replaceAll("g", "k’");
        mod = mod.replaceAll("K", "tK");
        mod = mod.replaceAll("sS", "S");
        mod = mod.replaceAll("SS", "S");
        mod = mod.replaceAll("ll", "l");
        mod = mod.replaceAll("jj", "j");
        mod = mod.replaceAll("ww", "w");
        mod = mod.replaceAll("’w", "w");
        mod = mod.replaceAll("nj", "J");
        mod = mod.replaceAll("nw", "Nw");

        trentTextField.setText(mod);
    }


    private void formRoots(JTextField pTerrTextField, JTextField pTrentTextField, JTextField trentTextField)
    {   pTerrTextField.setText("");
        StringBuffer out = new StringBuffer();
        
        // Root shape
        
        int size = fount.nextInt(100);
        
        // C
        produceCons(out);
        // CV
        produceVow(out);
        
        if (size < 30)
        { pTerrTextField.setText(out.toString());
          mutate(new String(out), pTrentTextField, trentTextField);
          return;
        }
        
        // CVC
        produceCons(out);
        // CVCV
        produceVow(out);
        
        if (size < 80)
        { pTerrTextField.setText(out.toString());
          mutate(new String(out), pTrentTextField, trentTextField);
          return;
        }
        
        // CVCVC
        produceCons(out);
        // CVCVCV
        produceVow(out);
        
        pTerrTextField.setText(out.toString());
        mutate(new String(out), pTrentTextField, trentTextField);
        return;

    }
    
    private void produceCons(StringBuffer out)
    {   int dispensed = fount.nextInt(15);
            
        if (dispensed < 3) 
        { switch (fount.nextInt(7))
          { case 0:
              out.append("pr");
              break;
            case 1:
              out.append("tr");
              break;
            case 2:
              out.append("c");
              break;
            case 3:
              out.append("cr");
              break;
            case 4:
              out.append("kr");
              break;
            case 5:
              out.append("J");
              break;
            case 6:
              out.append("?r");
              break;
          }
          return;
        }
        else if (dispensed < 8)
        { switch (fount.nextInt(7))
          { case 0:
              out.append("k");
              break;
            case 1:
              out.append("m");
              break;
            case 2:
              out.append("N");
              break;
            case 3:
              out.append("sr");
              break;
            case 4:
              out.append("?");
              break;
            case 5:
              out.append("h");
              break;
            case 6:
              out.append("p");
              break;
          }
          return;
        }
        else 
          switch (fount.nextInt(4))
          { case 0:
              out.append("t");
              break;
            case 1:
              out.append("n");
              break;
            case 2:
              out.append("s");
              break;
            case 3:
              out.append("r");
              break;
          }
        return;
    }

    private void produceVow(StringBuffer out)
    {   int dispensed = fount.nextInt(15);
    
        if (dispensed < 3) 
        { switch (fount.nextInt(7))
          { case 0:
              out.append("l:");
              break;
            case 1:
              out.append("l");
              break;
            case 2:
              out.append("la");
              break;
            case 3:
              out.append("le");
              break;
            case 4:
              out.append("li");
              break;
            case 5:
              out.append("lo");
              break;
            case 6:
              out.append("lu");
              break;
          }
          return;
        }
        else if (dispensed < 8)
        { switch (fount.nextInt(5))
          { case 0:
              out.append("a:");
              break;
            case 1:
              out.append("e:");
              break;
            case 2:
              out.append("i:");
              break;
            case 3:
              out.append("o:");
              break;
            case 4:
              out.append("u:");
              break;
          }
          return;
        }
        else 
          switch (fount.nextInt(5))
          { case 0:
              out.append("a");
              break;
            case 1:
              out.append("e");
              break;
            case 2:
              out.append("i");
              break;
            case 3:
              out.append("o");
              break;
            case 4:
              out.append("u");
              break;
          }
        return;
    }
    


    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TrentRoots2().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField pteFirstTextField;
    private javax.swing.JRadioButton thirdButton;
    private javax.swing.JTextField ptrThirdTextField;
    private javax.swing.JButton selButton;
    private javax.swing.JTextField ptrSecondTextField;
    private javax.swing.JTextField pteThirdTextField;
    private javax.swing.JLabel ptrLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton genButton;
    private javax.swing.JTextField trSecondTextField;
    private javax.swing.JTextField trFirstTextField;
    private javax.swing.JTextArea htmlArea;
    private javax.swing.JTextField pteSecondTextField;
    private javax.swing.JLabel trLabel;
    private javax.swing.JLabel pteLabel;
    private javax.swing.JTextField ptrFirstTextField;
    private javax.swing.JRadioButton secondButton;
    private javax.swing.JTextField trThirdTextField;
    private javax.swing.JRadioButton firstButton;
    // End of variables declaration//GEN-END:variables

    public java.util.Random fount = new java.util.Random();    
    
}
